//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        [Key]
        public int IdDepartments { get; set; }
        public string Name { get; set; }
        public string HeadOfDepartment { get; set; }
   
        public ICollection<BudgetAllocations> BudgetAllocations { get; set; }
        public ICollection<Employees> Employees { get; set; }
        public ICollection<Equipments> Equipments { get; set; }
        public ICollection<Locations> Locations { get; set; }
        public ICollection<Students> Students { get; set; }
    }
}
