//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using InventoryManagement.Models;

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipments
    {
        [Key]
        public int IdEquipment { get; set; }
        public string Name { get; set; }
        public string Serial_Number { get; set; }
        [ForeignKey(nameof(Categories))]
        public int CategoryID { get; set; }
        [ForeignKey(nameof(Departments))]
        public int DepartmentID { get; set; }
        [ForeignKey(nameof(Locations))]
        public int LocationID { get; set; }
        [ForeignKey(nameof(EquipmentStatus))]
        public int StatusID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpiration { get; set; }
        [ForeignKey(nameof(Suppliers))]
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public Categories Categories { get; set; }
        public Departments Departments { get; set; }
        public EquipmentStatus EquipmentStatus { get; set; }
        public Locations Locations { get; set; }
        public Suppliers Suppliers { get; set; }
        
        public virtual ICollection<InventoryMovements> InventoryMovements { get; set; }
        public virtual ICollection<MaintenanceRecords> MaintenanceRecords { get; set; }
        public virtual ICollection<UtilizationRecords> UtilizationRecords { get; set; }
        public virtual ICollection<WarrantyClaims> WarrantyClaims { get; set; }
    }
}
