//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMovements
    {
        [Key]
        public int IdMovement { get; set; }
        [ForeignKey(nameof(Equipments))]
        public int EquipmentID { get; set; }
        [ForeignKey(nameof(Locations))]
        public int FromLocationID { get; set; }
        [ForeignKey(nameof(Locations1))]
        public int ToLocationID { get; set; }
        public System.DateTime MovementDate { get; set; }
        [ForeignKey(nameof(Employees))]
        public int MovedByEmployeeID { get; set; }
        [ForeignKey(nameof(Employees1))]
        public Nullable<int> ReceivedByEmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual Equipments Equipments { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Locations Locations1 { get; set; }
    }
}
