//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Students
    {
public Students()
        {
            this.UtilizationRecords = new HashSet<UtilizationRecords>();
        }
        [Key]
        public int IdStudents { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string StudentIDСard { get; set; }
        [ForeignKey(nameof(Departments))]
        public int DepartmentID { get; set; }
        public string Course { get; set; }
    
        public Departments Departments { get; set; } 
        public ICollection<UtilizationRecords> UtilizationRecords { get; set; }
    }
}
