//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilizationRecords
    {
        [Key]
        public int IdUtilization { get; set; }
        [ForeignKey(nameof(Equipments))]
        public int EquipmentID { get; set; }
        [ForeignKey(nameof(Students))]
        public Nullable<int> StudentID { get; set; }
        [ForeignKey(nameof(Employees))]
        public Nullable<int> EmployeeID { get; set; }
        public System.DateTime UsageStart { get; set; }
        public Nullable<System.DateTime> UsageEnd { get; set; }
        public string Purpose { get; set; }
    
        public Employees Employees { get; set; }
        public Equipments Equipments { get; set; }
        public Students Students { get; set; }
    }
}
