//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipments
    {
        [Key]
        public int IdEquipment { get; set; }
        public string Name { get; set; }
        public string Serial_Number { get; set; }
        public int CategoryID { get; set; }
        public int DepartmentID { get; set; }
        public int LocationID { get; set; }
        public int StatusID { get; set; }
        public System.DateTime PurchaseDate { get; set; }
        public Nullable<System.DateTime> WarrantyExpiration { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> Cost { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Departments Departments { get; set; }
        public virtual EquipmentStatus EquipmentStatus { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Suppliers Suppliers { get; set; }

    }
}
