//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using InventoryManagement.Models;
using Microsoft.EntityFrameworkCore;

namespace InventoryManagment.Models
{
    using System;
    using System.Linq;
    
    public partial class InventoryManagmentEntities : DbContext
    {
        public InventoryManagmentEntities()
        {
            // Database.EnsureDeleted();
            if (Database.EnsureCreated())
            {
                Departments.AddRange(new Departments[]
                {
                    new Departments(){ Name = "Department1", HeadOfDepartment = "Head1"},
                    new Departments(){ Name = "Department2", HeadOfDepartment = "Head2"},
                });
                SaveChanges();
                BudgetAllocations.AddRange(new BudgetAllocations[]
                {
                    new BudgetAllocations(){ AllocationDate = DateTime.Now, DepartmentID = 1, Amount = 1233214, 
                        Purpose = "Purpose1"},
                    new BudgetAllocations(){ AllocationDate = new DateTime(19,10,9), DepartmentID = 2, Amount = 1233214, 
                        Purpose = "Purpose2"},
                });
                SaveChanges();
                
                EquipmentStatus.AddRange(new EquipmentStatus[]
                {
                    new EquipmentStatus(){Name = "Установлен", Description = "Установлен на место"},
                    new EquipmentStatus(){Name = "На складе", Description = "Находится на складе"},
                });
                SaveChanges();
                Suppliers.AddRange(new []
                {
                    new Suppliers(){Name = "Supplier1", ContactInfo = "ContactInfo1", Adress = "Address1", Email = "Email1"},
                    new Suppliers(){Name = "Supplier2", ContactInfo = "ContactInfo2", Adress = "Address2", Email = "Email2"},
                });

                SaveChanges();
                Categories.AddRange(new []
                {
                    new Categories(){Name="Name1", Description = "Description1"},
                    new Categories(){Name="Name2", Description = "Description2"},
                });
                SaveChanges();
                Locations.AddRange(new []
                {
                    new Locations(){Description = "Description1", DepartmentID = 1},
                    new Locations(){Description = "Description2", DepartmentID = 2},
                });
                SaveChanges();
            }
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            optionsBuilder.UseSqlite("Data Source=InventoryManagment.db");
        }
        
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Employees>()
                .HasMany(e => e.MovedInventory)
                .WithOne(m => m.MovedByEmployee)
                .HasForeignKey(m => m.MovedByEmployeeID)
                .OnDelete(DeleteBehavior.Restrict);

            modelBuilder.Entity<Employees>()
                .HasMany(e => e.ReceivedInventoryMovements)
                .WithOne(m => m.ReceivedByEmployee)
                .HasForeignKey(m => m.ReceivedByEmployeeID)
                .OnDelete(DeleteBehavior.Restrict);

            modelBuilder.Entity<Employees>()
                .HasMany(e => e.MaintenanceRecords)
                .WithOne(m => m.Employees)
                .HasForeignKey(m => m.PerformedByEmployeeID)
                .OnDelete(DeleteBehavior.Restrict);
            
            modelBuilder.Entity<Equipments>()
                .HasMany(e => e.MaintenanceRecords)
                .WithOne(m => m.Equipments)
                .HasForeignKey(m => m.EquipmentID)
                .OnDelete(DeleteBehavior.Restrict);
            
            modelBuilder.Entity<Locations>()
                .HasMany(e => e.FromLocation)
                .WithOne(m => m.FromLocation)
                .HasForeignKey(m => m.FromLocationID)
                .OnDelete(DeleteBehavior.Restrict);
            
            modelBuilder.Entity<Locations>()
                .HasMany(e => e.ToLocation)
                .WithOne(m => m.ToLocation)
                .HasForeignKey(m => m.ToLocationID)
                .OnDelete(DeleteBehavior.Restrict);

        }

        public virtual DbSet<Audits> Audits { get; set; }
        public virtual DbSet<BudgetAllocations> BudgetAllocations { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Equipments> Equipments { get; set; }
        public virtual DbSet<EquipmentStatus> EquipmentStatus { get; set; }
        public virtual DbSet<InventoryMovements> InventoryMovements { get; set; }
        public virtual DbSet<Locations> Locations { get; set; }
        public virtual DbSet<MaintenanceRecords> MaintenanceRecords { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Students> Students { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<UtilizationRecords> UtilizationRecords { get; set; }
        public virtual DbSet<WarrantyClaims> WarrantyClaims { get; set; }

    }
}
