//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [Key]
        public int IdOrder { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int SupplierID { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public string OrderItems { get; set; }
    
        public virtual Suppliers Suppliers { get; set; }
    }
}
