//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMovements
    {
        public int IdMovement { get; set; }
        public int EquipmentID { get; set; }
        public int FromLocationID { get; set; }
        public int ToLocationID { get; set; }
        public System.DateTime MovementDate { get; set; }
        public int MovedByEmployeeID { get; set; }
        public Nullable<int> ReceivedByEmployeeID { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Employees Employees1 { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Locations Locations { get; set; }
        public virtual Locations Locations1 { get; set; }
    }
}
