//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UtilizationRecords
    {
        public int IdUtilization { get; set; }
        public int EquipmentID { get; set; }
        public int StudentID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime UsageStart { get; set; }
        public Nullable<System.DateTime> UsageEnd { get; set; }
        public string Purpose { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual Equipment Equipment { get; set; }
        public virtual Students Students { get; set; }
    }
}
